// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace VSIXProjectMultiLang
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidVSIXProjectMultiLangPackageString = "04cdc06a-6f85-4271-8905-882745183d53";
        public static Guid guidVSIXProjectMultiLangPackage = new Guid(guidVSIXProjectMultiLangPackageString);

        public const string guidVSIXProjectMultiLangPackageCmdSetString = "d7d69c46-e99c-4a3c-95b8-9ac3a1e45289";
        public static Guid guidVSIXProjectMultiLangPackageCmdSet = new Guid(guidVSIXProjectMultiLangPackageCmdSetString);

        public const string guidImagesString = "6612c260-77de-4c37-873d-ca7f64d0e5ef";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages1String = "312209eb-317b-4919-a13e-736991b8ee18";
        public static Guid guidImages1 = new Guid(guidImages1String);

        public const string guidImages2String = "fa7297ee-bef4-4094-8e0f-7da2e3688e79";
        public static Guid guidImages2 = new Guid(guidImages2String);

        public const string guidImages3String = "4000725c-b993-4159-808d-f7a1bf73a3f7";
        public static Guid guidImages3 = new Guid(guidImages3String);

        public const string guidImages4String = "99cd7540-f693-4afd-a1cb-d96aa11b7abb";
        public static Guid guidImages4 = new Guid(guidImages4String);

        public const string guidImages5String = "ed2f2b06-746f-41d3-b70b-31493600a3d9";
        public static Guid guidImages5 = new Guid(guidImages5String);

        public const string guidImages6String = "bac9a47e-d78a-43d6-b966-3d480a3442aa";
        public static Guid guidImages6 = new Guid(guidImages6String);

        public const string guidImages7String = "240870d0-2bf8-4ac0-8ff0-8d5244b2bd33";
        public static Guid guidImages7 = new Guid(guidImages7String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int Command1Id = 0x0100;
        public const int cmdidCommandMoveToEnd = 0x1021;
        public const int cmdidCommandSelectCurrentMethod = 0x1022;
        public const int cmdidCommandToggle = 0x1023;
        public const int cmdidCommandAddChinese = 0x1024;
        public const int cmdidCommandToVar = 0x1025;
        public const int cmdidCommandConvToVar = 0x1026;
        public const int cmdidCommandConvToBool = 0x1027;
        public const int cmdidCommandConvToInt = 0x1028;
        public const int cmdidCommandConvToDouble = 0x1029;
        public const int cmdidCommandConvToString = 0x102A;
        public const int cmdidCommandGoToFile = 0x102B;
        public const int cmdidPostfixVar = 0x102C;
        public const int cmdidCommandConvToEng = 0x102D;
        public const int cmdidCommandMoveToIfBegin = 0x102E;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}